maintainer       "Scalr Inc."
maintainer_email "packages@scalr.net"
license          "All rights reserved"
description      "Installs/Configures reboot"
version          "0.0.1"
name             "reboot"
